<?php
return array (
  'title' => '院校分类',
  'style' => '0',
  'setting' => 
  array (
    'level' => '0',
  ),
  'siteid' => '0',
  'data' => 
  array (
    46 => 
    array (
      'linkageid' => '46',
      'name' => '综合类',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '46',
      'keyid' => '45',
      'listorder' => '0',
      'description' => '综合类',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
    ),
    448 => 
    array (
      'linkageid' => '448',
      'name' => '理工类',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '448',
      'keyid' => '45',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    449 => 
    array (
      'linkageid' => '449',
      'name' => '财经类',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '449',
      'keyid' => '45',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    450 => 
    array (
      'linkageid' => '450',
      'name' => '师范类',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '450',
      'keyid' => '45',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    451 => 
    array (
      'linkageid' => '451',
      'name' => '语言类',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '451',
      'keyid' => '45',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    452 => 
    array (
      'linkageid' => '452',
      'name' => '政法类',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '452',
      'keyid' => '45',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    453 => 
    array (
      'linkageid' => '453',
      'name' => '民族类',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '453',
      'keyid' => '45',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    454 => 
    array (
      'linkageid' => '454',
      'name' => '农林类',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '454',
      'keyid' => '45',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    455 => 
    array (
      'linkageid' => '455',
      'name' => '医药类',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '455',
      'keyid' => '45',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    456 => 
    array (
      'linkageid' => '456',
      'name' => '艺术类',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '456',
      'keyid' => '45',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    457 => 
    array (
      'linkageid' => '457',
      'name' => '体育类',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '457',
      'keyid' => '45',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    458 => 
    array (
      'linkageid' => '458',
      'name' => '军事类',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '458',
      'keyid' => '45',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
  ),
);
?>