<?php
return array (
  'title' => '门类',
  'style' => '1',
  'setting' => 
  array (
  ),
  'siteid' => '0',
  'data' => 
  array (
    511 => 
    array (
      'linkageid' => '511',
      'name' => '哲学',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '511',
      'keyid' => '510',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
    ),
    512 => 
    array (
      'linkageid' => '512',
      'name' => '经济学',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '512',
      'keyid' => '510',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
    ),
    513 => 
    array (
      'linkageid' => '513',
      'name' => '管理学',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '513',
      'keyid' => '510',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
    ),
    514 => 
    array (
      'linkageid' => '514',
      'name' => '法学',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '514',
      'keyid' => '510',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
    ),
    515 => 
    array (
      'linkageid' => '515',
      'name' => '教育学',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '515',
      'keyid' => '510',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
    ),
    516 => 
    array (
      'linkageid' => '516',
      'name' => '文学',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '516',
      'keyid' => '510',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
    ),
    517 => 
    array (
      'linkageid' => '517',
      'name' => '历史学',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '517',
      'keyid' => '510',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
    ),
    518 => 
    array (
      'linkageid' => '518',
      'name' => '理学',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '518',
      'keyid' => '510',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
    ),
    519 => 
    array (
      'linkageid' => '519',
      'name' => '工学',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '519',
      'keyid' => '510',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
    ),
    520 => 
    array (
      'linkageid' => '520',
      'name' => '农学',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '520',
      'keyid' => '510',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
    ),
    521 => 
    array (
      'linkageid' => '521',
      'name' => '医学',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '521',
      'keyid' => '510',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
    ),
    522 => 
    array (
      'linkageid' => '522',
      'name' => '艺术',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '522',
      'keyid' => '510',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
    ),
    523 => 
    array (
      'linkageid' => '523',
      'name' => '军事学',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '523',
      'keyid' => '510',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
    ),
  ),
);
?>