<?php
return array (
  0 => 
  array (
    'id' => '93',
    'catid' => '3846',
    'typeid' => '1',
    'title' => '中国社会科学院研究生院金融风险管理方向高级课程班招生简章（符合条件者可申请博士学位）',
    'style' => '',
    'thumb' => 'https://img.zhikunet.org/uploadfile/2019/0723/20190723031652288.jpg',
    'keywords' => '金融学 在职博士',
    'description' => '中国社会科学院研究生院金融风险管理方向高级课程班招生简章（符合条件者可申请博士学位）',
    'posids' => '0',
    'url' => 'https://ww.zhikunet.org/index.php?app=content&controller=index&view=show&catid=3846&id=93',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1565769084',
    'updatetime' => '1565769117',
    'school' => '13',
    'region' => '40',
  ),
  1 => 
  array (
    'id' => '92',
    'catid' => '3846',
    'typeid' => '1',
    'title' => '中国社会科学院研究生院房地产金融学方向高级课程班招生简章（符合条件者可申请博士学位）',
    'style' => '',
    'thumb' => 'https://img.zhikunet.org/uploadfile/2019/0723/20190723031652287.jpg',
    'keywords' => '金融学 在职博士',
    'description' => '中国社会科学院研究生院房地产金融学方向高级课程班招生简章（符合条件者可申请博士学位）',
    'posids' => '0',
    'url' => 'https://ww.zhikunet.org/index.php?app=content&controller=index&view=show&catid=3846&id=92',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1565769083',
    'updatetime' => '1565769116',
    'school' => '13',
    'region' => '40',
  ),
  2 => 
  array (
    'id' => '91',
    'catid' => '3846',
    'typeid' => '1',
    'title' => '中国社会科学院研究生院金融工程学方向高级课程班招生简章（符合条件者可申请博士学位）',
    'style' => '',
    'thumb' => 'https://img.zhikunet.org/uploadfile/2019/0723/20190723031652286.jpg',
    'keywords' => '金融学 在职博士',
    'description' => '中国社会科学院研究生院金融工程学方向高级课程班招生简章（符合条件者可申请博士学位）',
    'posids' => '0',
    'url' => 'https://ww.zhikunet.org/index.php?app=content&controller=index&view=show&catid=3846&id=91',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1565769082',
    'updatetime' => '1565769115',
    'school' => '13',
    'region' => '40',
  ),
  3 => 
  array (
    'id' => '90',
    'catid' => '3846',
    'typeid' => '1',
    'title' => '中国社会科学院研究生院货币理论与货币政策方向高级课程班招生简章（符合条件者可申请博士学位）',
    'style' => '',
    'thumb' => 'https://img.zhikunet.org/uploadfile/2019/0723/20190723031652285.jpg',
    'keywords' => '金融学 在职博士',
    'description' => '中国社会科学院研究生院货币理论与货币政策方向高级课程班招生简章（符合条件者可申请博士学位）',
    'posids' => '0',
    'url' => 'https://ww.zhikunet.org/index.php?app=content&controller=index&view=show&catid=3846&id=90',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1565769081',
    'updatetime' => '1565769114',
    'school' => '13',
    'region' => '40',
  ),
  4 => 
  array (
    'id' => '89',
    'catid' => '3846',
    'typeid' => '1',
    'title' => '中国社会科学院研究生院资金流量全球金融体系研究分析方向高级课程班招生简章（符合条件者可申请博士学位）',
    'style' => '',
    'thumb' => 'https://img.zhikunet.org/uploadfile/2019/0723/20190723031652284.jpg',
    'keywords' => '金融学 在职博士',
    'description' => '中国社会科学院研究生院资金流量全球金融体系研究分析方向高级课程班招生简章（符合条件者可申请博士学位）',
    'posids' => '0',
    'url' => 'https://ww.zhikunet.org/index.php?app=content&controller=index&view=show&catid=3846&id=89',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1565769080',
    'updatetime' => '1565769113',
    'school' => '13',
    'region' => '40',
  ),
  5 => 
  array (
    'id' => '88',
    'catid' => '3846',
    'typeid' => '1',
    'title' => '中国社会科学院研究生院金融市场理论与实践方向高级课程班招生简章（符合条件者可申请博士学位）',
    'style' => '',
    'thumb' => 'https://img.zhikunet.org/uploadfile/2019/0723/20190723031652283.jpg',
    'keywords' => '金融学 在职博士',
    'description' => '中国社会科学院研究生院金融市场理论与实践方向高级课程班招生简章（符合条件者可申请博士学位）',
    'posids' => '0',
    'url' => 'https://ww.zhikunet.org/index.php?app=content&controller=index&view=show&catid=3846&id=88',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1565769079',
    'updatetime' => '1565769112',
    'school' => '13',
    'region' => '40',
  ),
  6 => 
  array (
    'id' => '87',
    'catid' => '3846',
    'typeid' => '1',
    'title' => '中国社会科学院研究生院国际金融方向高级课程班招生简章（符合条件者可申请博士学位）',
    'style' => '',
    'thumb' => 'https://img.zhikunet.org/uploadfile/2019/0723/20190723031652282.jpg',
    'keywords' => '金融学 在职博士',
    'description' => '中国社会科学院研究生院国际金融方向高级课程班招生简章（符合条件者可申请博士学位）',
    'posids' => '0',
    'url' => 'https://ww.zhikunet.org/index.php?app=content&controller=index&view=show&catid=3846&id=87',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1565769078',
    'updatetime' => '1565769111',
    'school' => '13',
    'region' => '40',
  ),
  7 => 
  array (
    'id' => '86',
    'catid' => '3846',
    'typeid' => '1',
    'title' => '中国社会科学院研究生院产权市场方向高级课程班招生简章（符合条件者可申请博士学位）',
    'style' => '',
    'thumb' => 'https://img.zhikunet.org/uploadfile/2019/0723/20190723031652281.jpg',
    'keywords' => '金融学 在职博士',
    'description' => '中国社会科学院研究生院产权市场方向高级课程班招生简章（符合条件者可申请博士学位）',
    'posids' => '0',
    'url' => 'https://ww.zhikunet.org/index.php?app=content&controller=index&view=show&catid=3846&id=86',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1565769077',
    'updatetime' => '1565769110',
    'school' => '13',
    'region' => '40',
  ),
  8 => 
  array (
    'id' => '85',
    'catid' => '3846',
    'typeid' => '1',
    'title' => '中国社会科学院研究生院企业并购与重组方向高级课程班招生简章（符合条件者可申请博士学位）',
    'style' => '',
    'thumb' => 'https://img.zhikunet.org/uploadfile/2019/0723/20190723031652280.jpg',
    'keywords' => '金融学 在职博士',
    'description' => '中国社会科学院研究生院企业并购与重组方向高级课程班招生简章（符合条件者可申请博士学位）',
    'posids' => '0',
    'url' => 'https://ww.zhikunet.org/index.php?app=content&controller=index&view=show&catid=3846&id=85',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1565769076',
    'updatetime' => '1565769109',
    'school' => '13',
    'region' => '40',
  ),
  9 => 
  array (
    'id' => '84',
    'catid' => '3846',
    'typeid' => '1',
    'title' => '中国社会科学院研究生院房地产营销与房地产投资策略方向高级课程班招生简章（符合条件者可申请博士学位）',
    'style' => '',
    'thumb' => 'https://img.zhikunet.org/uploadfile/2019/0723/20190723031652279.jpg',
    'keywords' => '金融学 在职博士',
    'description' => '中国社会科学院研究生院房地产营销与房地产投资策略方向高级课程班招生简章（符合条件者可申请博士学位）',
    'posids' => '0',
    'url' => 'https://ww.zhikunet.org/index.php?app=content&controller=index&view=show&catid=3846&id=84',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1565769075',
    'updatetime' => '1565769108',
    'school' => '13',
    'region' => '40',
  ),
  10 => 
  array (
    'id' => '83',
    'catid' => '3846',
    'typeid' => '1',
    'title' => '中国社会科学院研究生院风险投资与企业上市方向高级课程班招生简章（符合条件者可申请博士学位）',
    'style' => '',
    'thumb' => 'https://img.zhikunet.org/uploadfile/2019/0723/20190723031652278.jpg',
    'keywords' => '金融学 在职博士',
    'description' => '中国社会科学院研究生院风险投资与企业上市方向高级课程班招生简章（符合条件者可申请博士学位）',
    'posids' => '0',
    'url' => 'https://ww.zhikunet.org/index.php?app=content&controller=index&view=show&catid=3846&id=83',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1565769074',
    'updatetime' => '1565769107',
    'school' => '13',
    'region' => '40',
  ),
  11 => 
  array (
    'id' => '82',
    'catid' => '3846',
    'typeid' => '1',
    'title' => '中国社会科学院研究生院期货市场与金融衍生产品方向高级课程班招生简章（符合条件者可申请博士学位）',
    'style' => '',
    'thumb' => 'https://img.zhikunet.org/uploadfile/2019/0723/20190723031652277.jpg',
    'keywords' => '金融学 在职博士',
    'description' => '中国社会科学院研究生院期货市场与金融衍生产品方向高级课程班招生简章（符合条件者可申请博士学位）',
    'posids' => '0',
    'url' => 'https://ww.zhikunet.org/index.php?app=content&controller=index&view=show&catid=3846&id=82',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1565769073',
    'updatetime' => '1565769106',
    'school' => '13',
    'region' => '40',
  ),
  12 => 
  array (
    'id' => '81',
    'catid' => '3846',
    'typeid' => '1',
    'title' => '中国社会科学院研究生院资产证券化与项目融资方向高级课程班招生简章（符合条件者可申请博士学位）',
    'style' => '',
    'thumb' => 'https://img.zhikunet.org/uploadfile/2019/0723/20190723031652276.jpg',
    'keywords' => '金融学 在职博士',
    'description' => '中国社会科学院研究生院资产证券化与项目融资方向高级课程班招生简章（符合条件者可申请博士学位）',
    'posids' => '0',
    'url' => 'https://ww.zhikunet.org/index.php?app=content&controller=index&view=show&catid=3846&id=81',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1565769072',
    'updatetime' => '1565769105',
    'school' => '13',
    'region' => '40',
  ),
  13 => 
  array (
    'id' => '80',
    'catid' => '3846',
    'typeid' => '1',
    'title' => '中国社会科学院研究生院公司理财与财务管理方向高级课程班招生简章（符合条件者可申请博士学位）',
    'style' => '',
    'thumb' => 'https://img.zhikunet.org/uploadfile/2019/0723/20190723031652275.jpg',
    'keywords' => '金融学 在职博士',
    'description' => '中国社会科学院研究生院公司理财与财务管理方向高级课程班招生简章（符合条件者可申请博士学位）',
    'posids' => '0',
    'url' => 'https://ww.zhikunet.org/index.php?app=content&controller=index&view=show&catid=3846&id=80',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1565769071',
    'updatetime' => '1565769104',
    'school' => '13',
    'region' => '40',
  ),
  14 => 
  array (
    'id' => '79',
    'catid' => '3846',
    'typeid' => '1',
    'title' => '中国社会科学院研究生院金融产品创新方向高级课程班招生简章（符合条件者可申请博士学位）',
    'style' => '',
    'thumb' => 'https://img.zhikunet.org/uploadfile/2019/0723/20190723031652274.jpg',
    'keywords' => '金融学 在职博士',
    'description' => '中国社会科学院研究生院金融产品创新方向高级课程班招生简章（符合条件者可申请博士学位）',
    'posids' => '0',
    'url' => 'https://ww.zhikunet.org/index.php?app=content&controller=index&view=show&catid=3846&id=79',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1565769070',
    'updatetime' => '1565769103',
    'school' => '13',
    'region' => '40',
  ),
);
?>