<?php
return array (
  3378 => 
  array (
    'catid' => '3378',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '56',
    'parentid' => '0',
    'arrparentid' => '',
    'child' => '0',
    'arrchildid' => '',
    'catname' => '测试',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => '',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"meta_title":"","meta_keywords":"","meta_description":""}',
    'mobilesetting' => '',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => '',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'commenttmalleid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
);
?>