<?php
return array (
  61 => 
  array (
    'catid' => '61',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '15',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '61',
    'catname' => '学沭阳话',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => '/shuyang/',
    'items' => '69',
    'hits' => '0',
    'setting' => '{"workflowid":"4","ishtml":"1","content_ishtml":"1","create_to_html_root":"0","template_list":"default","category_template":"category_shuyang","list_template":"list_shuyang","show_template":"show_shuyang","meta_title":"","meta_keywords":"\\u6cad\\u9633\\u8bdd,\\u6cad\\u9633\\u8bdd\\u516d\\u7ea7,\\u6cad\\u9633\\u571f\\u8bdd","meta_description":"\\u60f3\\u5b66\\u6cad\\u9633\\u8bdd,\\u5c31\\u6765\\u6cad\\u9633\\u7f51\\u6cad\\u9633\\u8bdd\\u9891\\u9053","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"1","show_ruleid":"31"}',
    'mobilesetting' => 'array (
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'category_ruleid\' => \'35\',
  \'show_ruleid\' => \'36\',
)',
    'listorder' => '12',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'xuezuoyanghua',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'commenttmalleid' => '0',
    'meta_title' => '',
    'meta_keywords' => '沭阳话,沭阳话六级,沭阳土话',
    'meta_description' => '想学沭阳话,就来沭阳网沭阳话频道',
  ),
);
?>