<?php
return array (
  56 => 
  array (
    'catid' => '56',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '56,57',
    'catname' => '景区景点',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => '/jingqu/',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"1","content_ishtml":"1","create_to_html_root":"0","template_list":"default","category_template":"category_jingqu","list_template":"list_jingqu","show_template":"show_jingqu","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"1","show_ruleid":"31"}',
    'mobilesetting' => 'array (
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'category_ruleid\' => \'35\',
  \'show_ruleid\' => \'36\',
)',
    'listorder' => '8',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'jingqujingdian',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'commenttmalleid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  57 => 
  array (
    'catid' => '57',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '56',
    'arrparentid' => '0,56',
    'child' => '0',
    'arrchildid' => '57',
    'catname' => '沭阳景点景区',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'jingqu/',
    'url' => '/jingqu/jingdian/',
    'items' => '20',
    'hits' => '0',
    'setting' => '{"workflowid":"4","ishtml":"1","content_ishtml":"1","create_to_html_root":"0","template_list":"default","category_template":"category_jingqu","list_template":"list_jingqu","show_template":"show_jingqu","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"1","show_ruleid":"31"}',
    'mobilesetting' => 'array (
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'category_ruleid\' => \'35\',
  \'show_ruleid\' => \'36\',
)',
    'listorder' => '57',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'zuoyangjingdianjingqu',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'commenttmalleid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
);
?>