<?php
return array (
  1 => 
  array (
    'modelid' => '1',
    'siteid' => '1',
    'name' => '新闻文章',
    'description' => '资讯信息',
    'tablename' => 'news',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'sort' => '0',
    'type' => '0',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'module' => '',
  ),
  3 => 
  array (
    'modelid' => '3',
    'siteid' => '1',
    'name' => '图片模型',
    'description' => '活动图集',
    'tablename' => 'picture',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_picture',
    'list_template' => 'list_picture',
    'show_template' => 'show_picture',
    'js_template' => '',
    'sort' => '0',
    'type' => '0',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'module' => '',
  ),
  58 => 
  array (
    'modelid' => '58',
    'siteid' => '1',
    'name' => '课程简章',
    'description' => '招生简章',
    'tablename' => 'course',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_course',
    'list_template' => 'list_course',
    'show_template' => 'show_course',
    'js_template' => '',
    'sort' => '0',
    'type' => '0',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'module' => '',
  ),
  57 => 
  array (
    'modelid' => '57',
    'siteid' => '1',
    'name' => '考研工具',
    'description' => '考研工具',
    'tablename' => 'kaoyan',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_kaoyan',
    'list_template' => 'list_kaoyan',
    'show_template' => 'show_kaoyan',
    'js_template' => '',
    'sort' => '0',
    'type' => '0',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'module' => '',
  ),
);
?>