<?php
return array (
  'admin' => 
  array (
    'module' => 'admin',
    'name' => 'admin',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '{"admin_email":"web@05273.cn","maxloginfailedtimes":"8","minrefreshtime":"2","mail_type":"1","mail_server":"ssl:\\/\\/smtp.ym.163.com","mail_port":"465","category_ajax":"0","mail_user":"noreply@05273.cn","mail_auth":"1","mail_from":"沭阳网<noreply@05273.cn>","mail_password":"123456","errorlog_size":"20"}',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-10-18',
    'updatedate' => '2010-10-18',
  ),
  'member' => 
  array (
    'module' => 'member',
    'name' => '会员',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '{"allowregister":"1","choosemodel":"0","enablemailcheck":"0","enablcodecheck":"0","mobile_checktype":"2","user_sendsms_title":"","registerverify":"0","showapppoint":"0","rmb_point_rate":"10","defualtpoint":"1","defualtamount":"5","showregprotocol":"1","regprotocol":"<p>欢迎您注册成为沭阳网用户<\\/p>\\r\\n<p>请仔细阅读下面的协议，只有接受协议才能继续进行注册。<\\/p>\\r\\n<p>1．服务条款的确认和接纳<\\/p>\\r\\n<p>沭阳网用户服务的所有权和运作权归沭阳网拥有。沭阳网所提供的服务将按照有关章程、服务条款和操作规则严格执行。用户通过注册程序点击“我同意” 按钮，即表示用户与沭阳网达成协议并接受所有的服务条款。<\\/p>\\r\\n<p>2．沭阳网服务简介<\\/p>\\r\\n<p>沭阳网通过国际互联网为用户提供新闻及文章浏览、图片浏览、软件下载、网上留言和BBS论坛等服务。<\\/p>\\r\\n<p>用户必须：<\\/p>\\r\\n<p>1)购置设备，包括个人电脑一台、调制解调器一个及配备上网装置。<\\/p>\\r\\n<p>2)个人上网和支付与此服务有关的电话费用、网络费用。<\\/p>\\r\\n<p>用户同意：<\\/p>\\r\\n<p>1)提供及时、详尽及准确的个人资料。<\\/p>\\r\\n<p>2)不断更新注册资料，符合及时、详尽、准确的要求。所有原始键入的资料将引用为注册资料。<\\/p>\\r\\n<p>3)用户同意遵守《中华人民共和国保守国家秘密法》、《中华人民共和国计算机信息系统安全保护条例》、《计算机软件保护条例》等有关计算机及互联网规定的法律和法规、实施办法。在任何情况下，沭阳网合理地认为用户的行为可能违反上述法律、法规，沭阳网可以在任何时候，不经事先通知终止向该用户提供服务。用户应了解国际互联网的无国界性，应特别注意遵守当地所有有关的法律和法规。<\\/p>\\r\\n<p>3．服务条款的修改<\\/p>\\r\\n<p>沭阳网会不定时地修改服务条款，服务条款一旦发生变动，将会在相关页面上提示修改内容。如果您同意改动，则再一次点击“我同意”按钮。 如果您不接受，则及时取消您的用户使用服务资格。<\\/p>\\r\\n<p>4．服务修订<\\/p>\\r\\n<p>沭阳网保留随时修改或中断服务而不需知照用户的权利。沭阳网行使修改或中断服务的权利，不需对用户或第三方负责。<\\/p>\\r\\n<p>5．用户隐私制度<\\/p>\\r\\n<p>尊重用户个人隐私是沭阳网的 基本政策。沭阳网不会公开、编辑或透露用户的注册信息，除非有法律许可要求，或沭阳网在诚信的基础上认为透露这些信息在以下三种情况是必要的：<\\/p>\\r\\n<p>1)遵守有关法律规定，遵从合法服务程序。<\\/p>\\r\\n<p>2)保持维护沭阳网的商标所有权。<\\/p>\\r\\n<p>3)在紧急情况下竭力维护用户个人和社会大众的隐私安全。<\\/p>\\r\\n<p>4)符合其他相关的要求。<\\/p>\\r\\n<p>6．用户的帐号，密码和安全性<\\/p>\\r\\n<p>一旦注册成功成为沭阳网用户，您将得到一个密码和帐号。如果您不保管好自己的帐号和密码安全，将对因此产生的后果负全部责任。另外，每个用户都要对其帐户中的所有活动和事件负全责。您可随时根据指示改变您的密码，也可以结束旧的帐户重开一个新帐户。用户同意若发现任何非法使用用户帐号或安全漏洞的情况，立即通知沭阳网。<\\/p>\\r\\n<p>7．免责条款<\\/p>\\r\\n<p>用户明确同意网站服务的使用由用户个人承担风险。<\\/p>\\r\\n<p>沭阳网不作任何类型的担保，不担保服务一定能满足用户的要求，也不担保服务不会受中断，对服务的及时性，安全性，出错发生都不作担保。用户理解并接受：任何通过沭阳网服务取得的信息资料的可靠性取决于用户自己，用户自己承担所有风险和责任。<\\/p>\\r\\n<p>8．有限责任<\\/p>\\r\\n<p>沭阳网对任何直接、间接、偶然、特殊及继起的损害不负责任。<\\/p>\\r\\n<p>9．不提供零售和商业性服务<\\/p>\\r\\n<p>用户使用网站服务的权利是个人的。用户只能是一个单独的个体而不能是一个公司或实体商业性组织。用户承诺不经沭阳网同意，不能利用网站服务进行销售或其他商业用途。<\\/p>\\r\\n<p>10．用户责任<\\/p>\\r\\n<p>用户单独承担传输内容的责任。用户必须遵循：<\\/p>\\r\\n<p>1)从中国境内向外传输技术性资料时必须符合中国有关法规。<\\/p>\\r\\n<p>2)使用网站服务不作非法用途。<\\/p>\\r\\n<p>3)不干扰或混乱网络服务。<\\/p>\\r\\n<p>4)不在论坛BBS或留言簿发表任何与政治相关的信息。<\\/p>\\r\\n<p>5)遵守所有使用网站服务的网络协议、规定、程序和惯例。<\\/p>\\r\\n<p>6)不得利用本站危害国家安全、泄露国家秘密，不得侵犯国家社会集体的和公民的合法权益。<\\/p>\\r\\n<p>7)不得利用本站制作、复制和传播下列信息：<\\/p>\\r\\n<p>1、煽动抗拒、破坏宪法和法律、行政法规实施的；<\\/p>\\r\\n<p>2、煽动颠覆国家政权，推翻社会主义制度的；<\\/p>\\r\\n<p>3、煽动分裂国家、破坏国家统一的；<\\/p>\\r\\n<p>4、煽动民族仇恨、民族歧视，破坏民族团结的；<\\/p>\\r\\n<p>5、捏造或者歪曲事实，散布谣言，扰乱社会秩序的；<\\/p>\\r\\n<p>6、宣扬封建迷信、淫秽、色情、赌博、暴力、凶杀、恐怖、教唆犯罪的；<\\/p>\\r\\n<p>7、公然侮辱他人或者捏造事实诽谤他人的，或者进行其他恶意攻击的；<\\/p>\\r\\n<p>8、损害国家机关信誉的；<\\/p>\\r\\n<p>9、其他违反宪法和法律行政法规的；<\\/p>\\r\\n<p>10、进行商业广告行为的。<\\/p>\\r\\n<p>用户不能传输任何教唆他人构成犯罪行为的资料；不能传输长国内不利条件和涉及国家安全的资料；不能传输任何不符合当地法规、国家法律和国际法 律的资料。未经许可而非法进入其它电脑系统是禁止的。若用户的行为不符合以上的条款，沭阳网将取消用户服务帐号。<\\/p>\\r\\n<p>11．网站内容的所有权<\\/p>\\r\\n<p>沭阳网定义的内容包括：文字、软件、声音、相片、录象、图表；在广告中全部内容；电子邮件的全部内容；沭阳网为用户提供的商业信息。所有这些内容受版权、商标、标签和其它财产所有权法律的保护。所以，用户只能在沭阳网和广告商授权下才能使用这些内容，而不能擅自复制、篡改这些内容、或创造与内容有关的派生产品。<\\/p>\\r\\n<p>12．附加信息服务<\\/p>\\r\\n<p>用户在享用沭阳网提供的免费服务的同时，同意接受沭阳网提供的各类附加信息服务。<\\/p>\\r\\n<p>13．禁止列表<\\/p>\\r\\n<p>本站暂时只接受 QQ 邮箱的注册,非法注册将被锁定账户。<\\/p>\\r\\n<p>14．解释权<\\/p>\\r\\n<p>本注册协议的解释权归沭阳网所有。如果其中有任何条款与国家的有关法律相抵触，则以国家法律的明文规定为准。<\\/p>","registerverifymessage":" 尊敬的{username}你好，欢迎您注册成为沭阳网用户，您的账号需要邮箱认证，点击下面链接进行认证：{click}\\r\\n或者将网址复制到浏览器：{url}\\r\\n<br><br><br><br><br><br><br>\\r\\n以上为系统邮件，请勿直接回复，如需帮助请与web@05273.cn联系","forgetpassword":"尊敬的用户您好，这是您申请的沭阳网密码找回邮件，<br>请在一小时内点击下面链接进行操作：{click}\\r\\n或者将网址复制到浏览器：{url}<br><br><br>\\r\\nPS:打开后会分配一个新密码给您，并且会发邮件到您这信箱保存，过程缓慢请稍等！\\r\\n<br><br><br><br><br><br><br>\\r\\n以上为系统邮件，请勿直接回复，如需帮助请与web@05273.cn联系"}',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'mips' => 
  array (
    'module' => 'mips',
    'name' => '手机MIP',
    'url' => 'mips/',
    'iscore' => '0',
    'version' => '3.0',
    'description' => '手机MIP',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2015-11-08',
    'updatedate' => '2015-11-08',
  ),
  'api' => 
  array (
    'module' => 'api',
    'name' => 'API接口',
    'url' => 'api/',
    'iscore' => '1',
    'version' => '1.0',
    'description' => 'API接口',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2012-03-01',
    'updatedate' => '2012-03-01',
  ),
  'email' => 
  array (
    'module' => 'email',
    'name' => '邮件发送',
    'url' => 'email/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '发送投稿邮件',
    'setting' => '{"tmail_type":"1","tmail_server":"ssl:\\/\\/smtp.ym.163.com","tmail_port":"465","tmail_from":"新闻投稿<news@05273.cn>","tmail_auth":"1","tmail_user":"news@05273.cn","tmail_password":"123456"}',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2017-03-01',
    'updatedate' => '2017-03-01',
  ),
  'pay' => 
  array (
    'module' => 'pay',
    'name' => '支付',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'digg' => 
  array (
    'module' => 'digg',
    'name' => '顶一下',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'special' => 
  array (
    'module' => 'special',
    'name' => '专题',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'content' => 
  array (
    'module' => 'content',
    'name' => '内容模块',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'search' => 
  array (
    'module' => 'search',
    'name' => '全站搜索',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '{"fulltextenble":"1","relationenble":"1","suggestenable":"1","sphinxenable":"0","sphinxhost":"10.228.134.102","sphinxport":"9312","1":{"fulltextenble":"1","relationenble":"0","suggestenable":"0","sphinxenable":"1","sphinxhost":"172.16.53.59","sphinxport":"9312"}}',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'weather' => 
  array (
    'module' => 'weather',
    'name' => '天气信息',
    'url' => 'weather/',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '天气信息',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2012-03-01',
    'updatedate' => '2012-03-01',
  ),
  'scan' => 
  array (
    'module' => 'scan',
    'name' => '木马扫描',
    'url' => 'scan',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'attachment' => 
  array (
    'module' => 'attachment',
    'name' => '附件',
    'url' => 'attachment',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'block' => 
  array (
    'module' => 'block',
    'name' => '碎片',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'collection' => 
  array (
    'module' => 'collection',
    'name' => '采集模块',
    'url' => 'collection',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'dbsource' => 
  array (
    'module' => 'dbsource',
    'name' => '数据源',
    'url' => '',
    'iscore' => '1',
    'version' => '',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'template' => 
  array (
    'module' => 'template',
    'name' => '模板风格',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'cron' => 
  array (
    'module' => 'cron',
    'name' => '计划任务',
    'url' => 'cron/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '计划任务',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2014-10-25',
    'updatedate' => '2014-10-25',
  ),
  'announce' => 
  array (
    'module' => 'announce',
    'name' => '公告',
    'url' => 'announce/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '公告',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2012-02-14',
    'updatedate' => '2012-02-14',
  ),
  'comment' => 
  array (
    'module' => 'comment',
    'name' => '评论',
    'url' => 'comment/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '评论',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2012-02-14',
    'updatedate' => '2012-02-14',
  ),
  'link' => 
  array (
    'module' => 'link',
    'name' => '友情链接',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '{"1":{"is_post":"0","enablecheckcode":"1"}}',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'vote' => 
  array (
    'module' => 'vote',
    'name' => '投票',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => 'array (
  1 => 
  array (
    \'default_style\' => \'default\',
    \'vote_tp_template\' => \'vote_tp\',
    \'allowguest\' => \'1\',
    \'enabled\' => \'1\',
    \'interval\' => \'1\',
    \'credit\' => \'1\',
  ),
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'message' => 
  array (
    'module' => 'message',
    'name' => '短消息',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'mood' => 
  array (
    'module' => 'mood',
    'name' => '新闻心情',
    'url' => 'mood/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '新闻心情',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2012-02-14',
    'updatedate' => '2012-02-14',
  ),
  'formguide' => 
  array (
    'module' => 'formguide',
    'name' => '表单向导',
    'url' => 'formguide/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => 'formguide',
    'setting' => '{"allowmultisubmit":"1","interval":"5","allowunreg":"0","mailmessage":"\\u6709\\u65b0\\u7528\\u6237\\u63d0\\u4ea4\\u8868\\u5355\\u5411\\u5bfc\\u5185\\u5bb9\\uff01"}',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-10-20',
    'updatedate' => '2010-10-20',
  ),
  'waplogin' => 
  array (
    'module' => 'waplogin',
    'name' => '手机登录',
    'url' => 'mobile/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '手机门户',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2015-01-16',
    'updatedate' => '2015-01-16',
  ),
  'today' => 
  array (
    'module' => 'today',
    'name' => '更多头条',
    'url' => 'today/',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '更多头条',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2012-03-01',
    'updatedate' => '2012-03-01',
  ),
  'tag' => 
  array (
    'module' => 'tag',
    'name' => '标签向导',
    'url' => 'tag/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '标签向导',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2012-02-14',
    'updatedate' => '2012-02-14',
  ),
  'sms' => 
  array (
    'module' => 'sms',
    'name' => '短信平台',
    'url' => 'sms/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '短信平台',
    'setting' => '{"sms_enable":"1","userid":"300412","productid":"5182","sms_key":"HYSs2M1BJKt5wEGbZkvbM8rKX4eqHD2u"}',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2011-09-02',
    'updatedate' => '2011-09-02',
  ),
  'hot' => 
  array (
    'module' => 'hot',
    'name' => '热门标签',
    'url' => 'hot/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '热门标签',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2011-04-23',
    'updatedate' => '2011-04-23',
  ),
  'dianping' => 
  array (
    'module' => 'dianping',
    'name' => '点评模块',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => ' ',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2011-06-26',
    'updatedate' => '2011-06-26',
  ),
  'url' => 
  array (
    'module' => 'url',
    'name' => '外链管理',
    'url' => 'url/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '外链',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2012-03-07',
    'updatedate' => '2012-03-07',
  ),
  'fanghu' => 
  array (
    'module' => 'fanghu',
    'name' => '攻击日志',
    'url' => 'fanghu/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '攻击日志',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2013-07-17',
    'updatedate' => '2020-07-17',
  ),
  'license' => 
  array (
    'module' => 'license',
    'name' => '商业授权',
    'url' => 'license/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '商业授权',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2013-04-16',
    'updatedate' => '2013-04-16',
  ),
  'ssi' => 
  array (
    'module' => 'ssi',
    'name' => 'SSI标签',
    'url' => 'ssi/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => 'ssi标签向导',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2012-09-23',
    'updatedate' => '2012-09-23',
  ),
  'xihuan' => 
  array (
    'module' => 'xihuan',
    'name' => '喜欢模块',
    'url' => 'xihuan/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '喜欢模块',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2013-04-02',
    'updatedate' => '2013-04-02',
  ),
  'lichang' => 
  array (
    'module' => 'lichang',
    'name' => '新闻立场',
    'url' => 'lichang/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '新闻立场',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2013-05-29',
    'updatedate' => '2013-05-29',
  ),
  'mobile' => 
  array (
    'module' => 'mobile',
    'name' => '手机门户',
    'url' => 'mobile/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '手机门户',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2015-01-16',
    'updatedate' => '2015-01-16',
  ),
  'stats' => 
  array (
    'module' => 'stats',
    'name' => '统计模块',
    'url' => '',
    'iscore' => '0',
    'version' => '1.5',
    'description' => '',
    'setting' => ' ',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2016-11-22',
    'updatedate' => '2016-11-22',
  ),
  'jubao' => 
  array (
    'module' => 'jubao',
    'name' => '内容举报',
    'url' => 'jubao/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '内容举报',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2014-05-17',
    'updatedate' => '2020-05-17',
  ),
  'phone' => 
  array (
    'module' => 'phone',
    'name' => '便民电话',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '{"1":{"is_post":"0","enablecheckcode":"1"}}',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'kuaixun' => 
  array (
    'module' => 'kuaixun',
    'name' => '快讯推送',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '{"1":{"is_post":"0"}}',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'onlines' => 
  array (
    'module' => 'onlines',
    'name' => '在线用户',
    'url' => 'onlines/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '在线用户',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2014-05-17',
    'updatedate' => '2020-05-17',
  ),
  'xml' => 
  array (
    'module' => 'xml',
    'name' => 'XML管理',
    'url' => 'xml/',
    'iscore' => '1',
    'version' => '1.0',
    'description' => 'XML管理',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2012-03-01',
    'updatedate' => '2012-03-01',
  ),
  'zuixin' => 
  array (
    'module' => 'zuixin',
    'name' => '最新滚动',
    'url' => 'zuixin/',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '最新滚动',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2012-03-01',
    'updatedate' => '2012-03-01',
  ),
  'book' => 
  array (
    'module' => 'book',
    'name' => '留言板',
    'url' => 'book/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '{"is_check":"1","enablecheckcode":"0","telnotice":"0","mailnotice":"1","1":{"is_check":"1","enablecheckcode":"1","telnotice":"0","mailnotice":"1"}}',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2012-12-14',
    'updatedate' => '2012-12-14',
  ),
  'custom_search' => 
  array (
    'module' => 'custom_search',
    'name' => '搜索感知',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2016-04-07',
    'updatedate' => '2016-04-07',
  ),
  'shuyangtoday' => 
  array (
    'module' => 'shuyangtoday',
    'name' => '今日推荐',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '今日推荐',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2013-10-06',
    'updatedate' => '2013-10-06',
  ),
  'weixin' => 
  array (
    'module' => 'weixin',
    'name' => '微信',
    'url' => 'weixin/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '微信管理平台',
    'setting' => '{"1":{"token":"shuyangwangweixinapi","appid":"wx9524143fc583dbda","appsecret":"5c005cd898e8beade826adbfbe1ad4d2","openid":"oQJC-0dpAvKevqnLB7fA0drN3Sf0","thumb":"https:\\/\\/img.05273.cn\\/weixin\\/nopic.jpg","yixin_appid":"5c636134c46340f7b41fe77e7757bbc2","yixin_appsecret":"6df309b171514bb09a2288d1848c4308","kefus":"09:00","kefux":"18:00"}}',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2014-06-11',
    'updatedate' => '2014-06-11',
  ),
  'slider' => 
  array (
    'module' => 'slider',
    'name' => '幻灯管理',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2013-12-25',
    'updatedate' => '2013-12-25',
  ),
  'sign' => 
  array (
    'module' => 'sign',
    'name' => '签到系统',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => 'array (
  1 => 
  array (
    \'is_post\' => \'1\',
    \'enablecheckcode\' => \'0\',
  ),
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'zhuanlan' => 
  array (
    'module' => 'zhuanlan',
    'name' => '沭阳号',
    'url' => 'zhuanlan/',
    'iscore' => '0',
    'version' => '1.0.1',
    'description' => '沭阳号平台',
    'setting' => '{"1":{"status":"1","index_urlruleid":"50","show_urlruleid":"52"}}',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2017-03-10',
    'updatedate' => '2017-03-10',
  ),
);
?>