<?php
return array (
  27 => 
  array (
    'posid' => '27',
    'modelid' => '0',
    'catid' => '0',
    'name' => '习近平时间',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '27',
    'siteid' => '0',
    'thumb' => '',
  ),
  26 => 
  array (
    'posid' => '26',
    'modelid' => '20',
    'catid' => '0',
    'name' => '手机站首页视频',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '26',
    'siteid' => '1',
    'thumb' => '',
  ),
  25 => 
  array (
    'posid' => '25',
    'modelid' => '1',
    'catid' => '0',
    'name' => '国内导读首页',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '25',
    'siteid' => '1',
    'thumb' => '',
  ),
  24 => 
  array (
    'posid' => '24',
    'modelid' => '1',
    'catid' => '0',
    'name' => '推送到爆料台',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '24',
    'siteid' => '1',
    'thumb' => '',
  ),
  22 => 
  array (
    'posid' => '22',
    'modelid' => '3',
    'catid' => '8',
    'name' => '图片频道竖式',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '22',
    'siteid' => '1',
    'thumb' => '',
  ),
  17 => 
  array (
    'posid' => '17',
    'modelid' => '0',
    'catid' => '0',
    'name' => '新闻视频推荐',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '17',
    'siteid' => '0',
    'thumb' => '',
  ),
  16 => 
  array (
    'posid' => '16',
    'modelid' => '0',
    'catid' => '0',
    'name' => '视频首页热点',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '16',
    'siteid' => '0',
    'thumb' => '',
  ),
  15 => 
  array (
    'posid' => '15',
    'modelid' => '0',
    'catid' => '0',
    'name' => '视频首页头条',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '15',
    'siteid' => '0',
    'thumb' => '',
  ),
  14 => 
  array (
    'posid' => '14',
    'modelid' => '0',
    'catid' => '0',
    'name' => '视频首页焦点图',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '14',
    'siteid' => '0',
    'thumb' => '',
  ),
  13 => 
  array (
    'posid' => '13',
    'modelid' => '0',
    'catid' => '0',
    'name' => '沭阳人物志',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '13',
    'siteid' => '0',
    'thumb' => '',
  ),
  12 => 
  array (
    'posid' => '12',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页图片',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '12',
    'siteid' => '0',
    'thumb' => '',
  ),
  10 => 
  array (
    'posid' => '10',
    'modelid' => '0',
    'catid' => '0',
    'name' => '栏目首页和WAP图',
    'maxnum' => '9999',
    'extention' => '',
    'listorder' => '10',
    'siteid' => '0',
    'thumb' => '',
  ),
  9 => 
  array (
    'posid' => '9',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页大焦点图',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '9',
    'siteid' => '0',
    'thumb' => '',
  ),
  8 => 
  array (
    'posid' => '8',
    'modelid' => '58',
    'catid' => '3846',
    'name' => '首页院校推荐',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '8',
    'siteid' => '1',
    'thumb' => '',
  ),
  5 => 
  array (
    'posid' => '5',
    'modelid' => '1',
    'catid' => '0',
    'name' => '首页问答下方',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '5',
    'siteid' => '1',
    'thumb' => '',
  ),
  2 => 
  array (
    'posid' => '2',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页和WAP轮播',
    'maxnum' => '5',
    'extention' => '',
    'listorder' => '2',
    'siteid' => '0',
    'thumb' => '',
  ),
  1 => 
  array (
    'posid' => '1',
    'modelid' => '0',
    'catid' => '0',
    'name' => '全站_热门推荐',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '1',
    'siteid' => '0',
    'thumb' => '',
  ),
);
?>