<?php
return array (
  1 => 
  array (
    'typeid' => '1',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '同等博士',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'style' => '',
    'listorder' => '0',
    'description' => '',
  ),
  2 => 
  array (
    'typeid' => '2',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '同等硕士',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'style' => '',
    'listorder' => '0',
    'description' => '',
  ),
  3 => 
  array (
    'typeid' => '3',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '专业硕士',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'style' => '',
    'listorder' => '0',
    'description' => '',
  ),
  4 => 
  array (
    'typeid' => '4',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '中外办学',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'style' => '',
    'listorder' => '0',
    'description' => '',
  ),
  5 => 
  array (
    'typeid' => '5',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '留学硕士',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'style' => '',
    'listorder' => '0',
    'description' => '',
  ),
  6 => 
  array (
    'typeid' => '6',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '留学博士',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'style' => '',
    'listorder' => '0',
    'description' => '',
  ),
  7 => 
  array (
    'typeid' => '7',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '研修班',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'style' => '',
    'listorder' => '0',
    'description' => '',
  ),
  8 => 
  array (
    'typeid' => '8',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '内训',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'style' => '',
    'listorder' => '0',
    'description' => '',
  ),
);
?>