<?php
return array (
  1 => '{$categorydir}{$catdir}/index.html|{$categorydir}{$catdir}/list_{$page}.html',
  6 => 'index.php?app=content&controller=index&view=lists&catid={$catid}|index.php?app=content&controller=index&view=lists&catid={$catid}&page={$page}',
  11 => '{$catdir}/view_{$id}.html|{$catdir}/view_{$id}_{$page}.html',
  12 => '{$categorydir}{$catdir}/{$year}/{$month}{$day}/{$id}.html|{$categorydir}{$catdir}/{$year}/{$month}{$day}/{$id}_{$page}.html',
  16 => 'index.php?app=content&controller=index&view=show&catid={$catid}&id={$id}|index.php?app=content&controller=index&view=show&catid={$catid}&id={$id}&page={$page}',
  17 => 'show-{$catid}-{$id}-{$page}.html',
  18 => 'content-{$catid}-{$id}-{$page}.html',
  30 => 'list-{$catid}-{$page}.html',
  31 => '{$categorydir}{$catdir}/view_{$id}.html|{$categorydir}{$catdir}/view_{$id}_{$page}.html',
  49 => 'index.php?app=zhuanlan&controller=index|index.php?app=zhuanlan&controller=index&page={$page}',
  33 => '{$categorydir}{$catdir}/{$month}{$day}/view_{$id}.html|{$categorydir}{$catdir}/{$month}{$day}/view_{$id}_{$page}.html',
  34 => '{$catdir}/huati_{$month}{$day}_{$id}.html|{$catdir}/huati_{$month}{$day}_{$id}_{$page}.html',
  35 => 'list-{$catid}-1.html|list-{$catid}-{$page}.html',
  36 => 'show-{$catid}-{$id}-1.html|show-{$catid}-{$id}-{$page}.html',
  38 => 'show-{$catid}-{$id}-1.html|show-{$catid}-{$id}-{$page}.html',
  48 => 'mip-{$catid}-{$id}-1.html|mip-{$catid}-{$id}-{$page}.html',
  40 => '/{$catdir}/xz_{$typeid}_1.html|/{$catdir}/xz_{$typeid}_{$page}.html',
  41 => '/{$catdir}/xz_{$typeid}_1.html|/{$catdir}/xz_{$typeid}_{$page}.html',
  43 => 'miplist-{$catid}-1.html|miplist-{$catid}-{$page}.html',
  44 => '{$categorydir}{$catdir}/{$month}{$day}/view_{$id}.html|{$categorydir}{$catdir}/{$month}{$day}/view_{$id}_{$page}.html',
  45 => '{$categorydir}{$catdir}/view_{$id}.html|{$categorydir}{$catdir}/view_{$id}_{$page}.html',
  46 => '{$catdir}/huati_{$month}{$day}_{$id}.html|{$catdir}/huati_{$month}{$day}_{$id}_{$page}.html',
  47 => '{$categorydir}{$catdir}/index.html|{$categorydir}{$catdir}/list_{$page}.html',
  50 => '/u/index.html|/u/index_{$page}.html',
  51 => 'index.php?app=zhuanlan&controller=index&view=show&domain={$domain}|index.php?app=zhuanlan&controller=index&view=show&domain={$domain}&page={$page}',
  52 => '/index.html|/{$page}.html',
  53 => '{$categorydir}{$catdir}/{$month}{$day}/view_{$id}.html|{$categorydir}{$catdir}/{$month}{$day}/view_{$id}_{$page}.html',
  54 => '{$categorydir}{$catdir}/view_{$id}.html|{$categorydir}{$catdir}/view_{$id}_{$page}.html',
  55 => '{$catdir}/huati_{$month}{$day}_{$id}.html|{$catdir}/huati_{$month}{$day}_{$id}_{$page}.html',
  56 => '{$categorydir}{$catdir}/index.html|{$categorydir}{$catdir}/list_{$page}.html',
);
?>